{
 "title": "Cluster resources monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Utilisation CPU des nodes du cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "Microservice monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Nombre total d'erreur 404",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "flask_http_request_total{method=\"GET\",status=\"404\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durée des requêtes en ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_sum{method=\"GET\",path=\"/get_articles\",status=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}