---
- name: install php with all modules
  package: name={{ item }} state=present
  with_items:
    - php
    - php-curl
    - php-gd
    - php-cli
    - php-mysql
    - php-xml
    - php-mbstring
    - php-fpm
    - php-json
    - php-intl
    - php-zip

- name: start and enable service
  service: name=php8.2-fpm state=started enabled=yes

- name: restart php-fpm
  service: name=php8.2-fpm state=restarted